[package]
name = "cch23-maxiim3"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
shuttle-rocket = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.26.0"
env_logger = "0.10.1"
cargo-watch = "8.4.1"
